// <auto-generated />
using System;
using ApiStudyBuddy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiStudyBuddy.Migrations
{
    [DbContext(typeof(ApiStudyBuddyContext))]
    partial class ApiStudyBuddyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiStudyBuddy.Models.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeckId"));

                    b.Property<string>("DeckDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeckName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");

                    b.HasData(
                        new
                        {
                            DeckId = 1,
                            DeckDescription = "Design patterns all about class instantiation",
                            DeckName = "Creational Design Patterns",
                            IsPublic = false,
                            ReadOnly = false
                        },
                        new
                        {
                            DeckId = 2,
                            DeckDescription = "Design patterns all about class and Object composition",
                            DeckName = "Structural Design Patterns",
                            IsPublic = false,
                            ReadOnly = false
                        },
                        new
                        {
                            DeckId = 3,
                            DeckDescription = "Design patterns all about Class's objects communication",
                            DeckName = "Behavorial Design Patterns",
                            IsPublic = false,
                            ReadOnly = false
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.DeckFlashCard", b =>
                {
                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("FlashCardId")
                        .HasColumnType("int");

                    b.HasKey("DeckId", "FlashCardId");

                    b.HasIndex("FlashCardId");

                    b.ToTable("DeckFlashCards");

                    b.HasData(
                        new
                        {
                            DeckId = 1,
                            FlashCardId = 1
                        },
                        new
                        {
                            DeckId = 1,
                            FlashCardId = 2
                        },
                        new
                        {
                            DeckId = 2,
                            FlashCardId = 3
                        },
                        new
                        {
                            DeckId = 2,
                            FlashCardId = 4
                        },
                        new
                        {
                            DeckId = 3,
                            FlashCardId = 5
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.DeckGroup", b =>
                {
                    b.Property<int>("DeckGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeckGroupId"));

                    b.Property<string>("DeckGroupDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeckGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("DeckGroupId");

                    b.ToTable("DeckGroups");

                    b.HasData(
                        new
                        {
                            DeckGroupId = 1,
                            DeckGroupDescription = "Solutions to commonly occurring problems in software design.",
                            DeckGroupName = "Design Patterns",
                            IsPublic = false,
                            ReadOnly = false
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.DeckGroupDeck", b =>
                {
                    b.Property<int>("DeckGroupId")
                        .HasColumnType("int");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.HasKey("DeckGroupId", "DeckId");

                    b.HasIndex("DeckId");

                    b.ToTable("DeckGroupDecks");

                    b.HasData(
                        new
                        {
                            DeckGroupId = 1,
                            DeckId = 1
                        },
                        new
                        {
                            DeckGroupId = 1,
                            DeckId = 2
                        },
                        new
                        {
                            DeckGroupId = 1,
                            DeckId = 3
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.FlashCard", b =>
                {
                    b.Property<int>("FlashCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlashCardId"));

                    b.Property<string>("FlashCardAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlashCardAnswerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlashCardQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlashCardQuestionImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("FlashCardId");

                    b.ToTable("FlashCards");

                    b.HasData(
                        new
                        {
                            FlashCardId = 1,
                            FlashCardAnswer = "Creates an instance of several families of classes",
                            FlashCardQuestion = "What is abstract factory",
                            IsPublic = true,
                            ReadOnly = true
                        },
                        new
                        {
                            FlashCardId = 2,
                            FlashCardAnswer = "A class of which only a single instance can exist",
                            FlashCardQuestion = "What is Singleton?",
                            IsPublic = true,
                            ReadOnly = true
                        },
                        new
                        {
                            FlashCardId = 3,
                            FlashCardAnswer = "Add responsibilites to objects dynamically",
                            FlashCardQuestion = "What is decorator?",
                            IsPublic = true,
                            ReadOnly = true
                        },
                        new
                        {
                            FlashCardId = 4,
                            FlashCardAnswer = "A single class that represents an entire subsystem",
                            FlashCardQuestion = "What is facade?",
                            IsPublic = true,
                            ReadOnly = true
                        },
                        new
                        {
                            FlashCardId = 5,
                            FlashCardAnswer = "Sequentially access the elements of a collection",
                            FlashCardQuestion = "What is iterator?",
                            IsPublic = true,
                            ReadOnly = true
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.StudySession", b =>
                {
                    b.Property<int>("StudySessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudySessionId"));

                    b.Property<int?>("DeckGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudySessionId");

                    b.HasIndex("DeckGroupId");

                    b.HasIndex("DeckId");

                    b.HasIndex("UserId");

                    b.ToTable("StudySessions");

                    b.HasData(
                        new
                        {
                            StudySessionId = 1,
                            DeckGroupId = 1,
                            DeckId = 1,
                            EndTime = new DateTime(2023, 9, 11, 15, 35, 15, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            StartTime = new DateTime(2023, 9, 11, 15, 5, 15, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.StudySessionFlashCard", b =>
                {
                    b.Property<int>("StudySessionId")
                        .HasColumnType("int");

                    b.Property<int>("FlashCardId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.HasKey("StudySessionId", "FlashCardId");

                    b.HasIndex("FlashCardId");

                    b.ToTable("StudySessionsFlashCards");

                    b.HasData(
                        new
                        {
                            StudySessionId = 1,
                            FlashCardId = 1,
                            IsCorrect = true
                        },
                        new
                        {
                            StudySessionId = 1,
                            FlashCardId = 2,
                            IsCorrect = false
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "JohnDoe@gmail.com",
                            FirstName = "John",
                            IsAdmin = false,
                            LastName = "Doe",
                            PasswordHash = "AQAAAAIAAYagAAAAEHkNcdcydJ6lCgu6hPLEdV8CezbujT87yOO2nMMXwe71pTX+CdelWp6WHAD+hNGN3w==",
                            Username = "JDoe1"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "MaryJane@gmail.com",
                            FirstName = "Mary",
                            IsAdmin = false,
                            LastName = "Jane",
                            PasswordHash = "AQAAAAIAAYagAAAAEFCYkHw0hLhF5AiysQpkKd5Y1DBCL0iJgPA/dQtXBzrbyuCHNqZOh8Db9rAZg1DrsA==",
                            Username = "MJane1"
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.UserDeck", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DeckId");

                    b.HasIndex("DeckId");

                    b.ToTable("UserDecks");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DeckId = 1
                        },
                        new
                        {
                            UserId = 1,
                            DeckId = 2
                        },
                        new
                        {
                            UserId = 1,
                            DeckId = 3
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.UserDeckGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DeckGroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DeckGroupId");

                    b.HasIndex("DeckGroupId");

                    b.ToTable("UserDeckGroups");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DeckGroupId = 1
                        });
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.DeckFlashCard", b =>
                {
                    b.HasOne("ApiStudyBuddy.Models.Deck", "Deck")
                        .WithMany("DeckFlashCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiStudyBuddy.Models.FlashCard", "FlashCard")
                        .WithMany("DeckFlashCards")
                        .HasForeignKey("FlashCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("FlashCard");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.DeckGroupDeck", b =>
                {
                    b.HasOne("ApiStudyBuddy.Models.DeckGroup", "DeckGroup")
                        .WithMany("DeckGroupDecks")
                        .HasForeignKey("DeckGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiStudyBuddy.Models.Deck", "Deck")
                        .WithMany("DeckGroupDecks")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("DeckGroup");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.StudySession", b =>
                {
                    b.HasOne("ApiStudyBuddy.Models.DeckGroup", "DeckGroup")
                        .WithMany("StudySessions")
                        .HasForeignKey("DeckGroupId");

                    b.HasOne("ApiStudyBuddy.Models.Deck", "Deck")
                        .WithMany("StudySessions")
                        .HasForeignKey("DeckId");

                    b.HasOne("ApiStudyBuddy.Models.User", "User")
                        .WithMany("StudySessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("DeckGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.StudySessionFlashCard", b =>
                {
                    b.HasOne("ApiStudyBuddy.Models.FlashCard", "FlashCard")
                        .WithMany("StudySessionFlashCards")
                        .HasForeignKey("FlashCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiStudyBuddy.Models.StudySession", "StudySession")
                        .WithMany("StudySessionFlashCards")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashCard");

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.UserDeck", b =>
                {
                    b.HasOne("ApiStudyBuddy.Models.Deck", "Deck")
                        .WithMany("UserDecks")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiStudyBuddy.Models.User", "User")
                        .WithMany("UserDecks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.UserDeckGroup", b =>
                {
                    b.HasOne("ApiStudyBuddy.Models.DeckGroup", "DeckGroup")
                        .WithMany("UserDeckGroups")
                        .HasForeignKey("DeckGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiStudyBuddy.Models.User", "User")
                        .WithMany("UserDeckGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeckGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.Deck", b =>
                {
                    b.Navigation("DeckFlashCards");

                    b.Navigation("DeckGroupDecks");

                    b.Navigation("StudySessions");

                    b.Navigation("UserDecks");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.DeckGroup", b =>
                {
                    b.Navigation("DeckGroupDecks");

                    b.Navigation("StudySessions");

                    b.Navigation("UserDeckGroups");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.FlashCard", b =>
                {
                    b.Navigation("DeckFlashCards");

                    b.Navigation("StudySessionFlashCards");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.StudySession", b =>
                {
                    b.Navigation("StudySessionFlashCards");
                });

            modelBuilder.Entity("ApiStudyBuddy.Models.User", b =>
                {
                    b.Navigation("StudySessions");

                    b.Navigation("UserDeckGroups");

                    b.Navigation("UserDecks");
                });
#pragma warning restore 612, 618
        }
    }
}
